apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: statusplattform-nais-operator
  namespace: navdig
  labels:
    team: navdig
spec:
  envFrom:
    - secret: swagger-api-konfig
  env:
    - name: RUST_BACKTRACE
      value: full
    - name: RUST_LOG
      value: kube=debug
    - name: COLORBT_SHOW_HIDDEN
      value: "1"
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  accessPolicy:
    outbound:
      rules:
        - application: portalserver
