apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: statusplattform-nais-operator
  namespace: navdig
  labels:
    team: navdig
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  accessPolicy:
    outbound:
      rules:
        - application: portalserver
