name: build
on: push

jobs:
  build: # building is also testing.
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: "write"
      contents: "read"
      id-token: "write"
    steps:
      - name: nix-build
        uses: nais/nais-nix-action@main
        id: nix-build
        with:
          team: navdig
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

    outputs:
      image: ${{ steps.nix-build.outputs.image }}
  deploy:
    name: deploy-dev
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: ${{ steps.build.outputs.image }}
          CLUSTER: dev-gcp
          RESOURCE: ./nais.yml
          VAR: image=${{ needs.build.outputs.image }}
