name: build
on:
  push:
    paths-ignore:
      - "**/*.md"
      - ".env*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: "write"
      contents: "read"
      id-token: "write"
    steps:
      - name: nix-build
        uses: nais/nais-nix-action@main
        id: nix-build
        with:
          team: navdig
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

    outputs:
      image: ${{ steps.nix-build.outputs.image }}

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: "write"
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - name: Download spec
        uses: actions/download-artifact@v4
        with:
          name: spec.yaml

      - name: Deploy-dev
        uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: ${{ steps.build.outputs.image }}
          CLUSTER: dev-gcp
          RESOURCE: spec.yaml

      - name: Deploy-prod
        if: contains(github.ref, 'refs/tags/v')
        uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: ${{ steps.build.outputs.image }}
          CLUSTER: prod-gcp
          RESOURCE: spec.yaml
